services:
    db__local:
        container_name: db__local
        image: postgres:17.4
        env_file: .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
