"""add cubic ods tables

Revision ID: 2fe879a1a59a
Revises:
Create Date: 2022-01-09 16:50:54.618557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fe879a1a59a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('prefix_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), nullable=False),
    sa.Column('snapshot', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('s3_modified', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefixes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('snapshot', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('snapshot_s3_key', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('s3_prefix', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefixes')
    op.drop_table('loads')
    # ### end Alembic commands ###
