
# base image (in line with .tools-version)
FROM python:3.7-slim

# set the working directory for separation of files
WORKDIR /data_platform
# copy everything in the repo over to working directory
COPY . .

# install all required packages
RUN pip install -r requirements.txt

# install supervisor for process management
RUN pip install supervisor

CMD ["echo", "Container 'main' ready!"]
