"""Add qlik replicate tables and loads

Revision ID: a3c9117b3310
Revises: 
Create Date: 2021-12-01 11:25:24.451921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3c9117b3310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubic_qlik_batch_loads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cubic_qlik_cdc_loads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cubic_qlik_tables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('s3_prefix', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cubic_qlik_tables')
    op.drop_table('cubic_qlik_cdc_loads')
    op.drop_table('cubic_qlik_batch_loads')
    # ### end Alembic commands ###
