
name: build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: "Environment, 'dev' or 'prod'."
        required: true
      s3_bucket_operations:
        description: "Operations S3 bucket."
        required: true

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # job env variables
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install python packages in 'libs' folder.
        working-directory: ${{github.workspace}}
        run: pip install -r requirements.txt -t ./libs

      - name: Create package to be used for Lambda and Glue Jobs, and add lambda files.
        working-directory: ${{github.workspace}}/aws/s3/lambdas
        run: zip -r ${{github.workspace}}/aws/s3/packages/data_platform.zip ./

      - name: Add 'data_platform' folder to package.
        working-directory: ${{github.workspace}}
        run: zip -r ${{github.workspace}}/aws/s3/packages/data_platform.zip ./data_platform/

      - name: Add python libs to package.
        working-directory: ${{github.workspace}}/libs
        run: zip -r ${{github.workspace}}/aws/s3/packages/data_platform.zip ./

      - name: Sync Glue Jobs and package to operations.
        run: aws s3 sync ${{github.workspace}}/aws/s3/ s3://${{github.event.inputs.s3_bucket_operations}}/ --exclude "*/empty"
