name: Docker Build

on: [push]

jobs:
  docker_ex_cubic_ingestion:
    name: Build Docker image for 'ex_cubic_ingestion' app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build .
      working-directory: ex_cubic_ingestion
